// LOGIN
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// HABITS
export const CREATE_HABIT = "CREATE_HABIT";
export const DELETE_HABIT = "DELETE_HABIT";

// RECORDS
export const UPDATE_RECORD = "UPDATE_RECORD";