// LOGIN
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// HABITS
export const CREATE_HABIT = "CREATE_HABIT";
export const DELETE_HABIT = "DELETE_HABIT";

// RECORDS
export const CREATE_RECORD = "CREATE_RECORD";
export const DELETE_RECORD = "RECORD_RECORD";